service: newrelic-log-ingestion

provider:
  name: aws
  region: us-west-2
  runtime: python3.9
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  timeout: 30
  deploymentBucket:
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies. Default is false

  # Uncomment this line to use your own IAM role
  #role: arn:aws:iam::YourAccountNumber:role/YourIamRole

  environment:
    # Determines if logs are forwarded to New Relic Infrastructure
    INFRA_ENABLED: ${env:INFRA_ENABLED, "False"}
    # Your NewRelic license key
    LICENSE_KEY: ${file(env.yml):${opt:stage}.LICENSE_KEY}
    # Determines if logs are forwarded to New Relic Logging
    LOGGING_ENABLED: ${env:LOGGING_ENABLED, "False"}
    # A boolean to determine if you want to output debug messages in the CloudWatch console
    DEBUG_LOGGING_ENABLED: ${env:DEBUG_LOGGING_ENABLED, "False"}

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: false
    fileName: ./src/requirements.txt

package:
  patterns:
    - '!./**'
    - ./LICENSE
    - ./src/function.py

functions:
  newrelic-log-ingestion:
    description: Send log data from CloudWatch Logs to New Relic Infrastructure (Cloud Integrations) and New Relic Logging.
    handler: src/function.lambda_handler
    name: newrelic-log-ingestion-${opt:stage}

plugins:
  - serverless-python-requirements
