# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

references:
  docker_image: &docker_image
    docker:
      - image: cimg/node:21.1.0
        environment:
          NODE_OPTIONS: --max_old_space_size=4096

  container_config: &container_config
    <<: *docker_image
    working_directory: ~/repo


  system_dependencies: &system_dependencies
    run:
      name: Install system requirements
      command: |
        sudo npm install -g serverless
        sls plugin install -n serverless-python-requirements


jobs:
  checkout_code:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

  deploy_test:
    <<: *container_config
    steps:
      - *system_dependencies
      - run:
          name: Bind Environment Variables
          command: |
            echo 'export LICENSE_KEY=$STAGING_LICENSE_KEY' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      - run: sls deploy --verbose


workflows:
  version: 2

  build-log-ingestion:
    jobs:
      - checkout_code
      - deploy_test:
          requires:
            - checkout_code
          filters:
            branches:
              only: circleci-project-setup #master



